# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: book-review
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpassword

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8005
    volumes:
      - .:/code
    ports:
      - "8005:8005"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://pguser:pgpassword@db:5432/book-review

volumes:
  postgres_data: